name: helloword
description: "A new Flutter project for Titik Kumpul Application."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  supabase_flutter: ^2.0.0
  image_picker: ^1.2.2
  intl: ^0.20.2
  http: ^1.2.0
  url_launcher: ^6.2.6
  flutter_dotenv: ^6.0.1
  flutter_map: ^8.3.0
  latlong2: ^0.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  # 🔥 SEKARANG REGISTER FOLDERNYA SAMPAI IMAGES BRO!
  assets:
    - assets/images/
    - .env

flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/images/icon.png"